### PR TITLE
fix: treat zero value outputs as pre-defined

### PR DESCRIPTION
**Pull request by kaladinlight**
Previously, outputs with a value of `0` were being treated as a split output. This change only treats outputs with a value of `undefined` as split outputs. This allows you to pass through a zero value script (OP_RETURN) output into the coinselect `split` function without it increasing the `splitOutputsCount`, resulting in a correct and expected result.

### CODE REVIEW

**Comment by junderw** [comment]
Please rebase (added Github Actions and package-lock etc.)

**Comment by kaladinlight** [comment]
> Please rebase (added Github Actions and package-lock etc.)

should be up to date now

**Review by junderw — APPROVED** [review]

**Comment by junderw** [comment]
published as 3.1.13

**Comment by kaladinlight** [comment]
> published as 3.1.13

Thanks for getting this in and published so quickly!

**Pull request merged**
