### PR TITLE
Add spend all utility

### PR DESCRIPTION
**Pull request by runn1ng**
If you think it is good idea, I will add tests.

### CODE REVIEW

**Comment by dcousens** [comment]
@afk11 interestingly,  I have typically done this by leaving `.value` undefined on a `coinselect/split`.

Maybe this is better though.

**Comment by runn1ng** [comment]
Oh, that makes sense, that didn't occur to me.

However, there is really a request from users to really "swipe all", including the small utxos that are detrimental. I am not sure why, but some people just want to see clear 0 on their balance, I guess.

So maybe it would be better to add that option to `split` and have `spendall` just as a redirection to `split`?

**Comment by runn1ng** [comment]
I have changed the utility to use `split`.... and now it is maybe too simple :)

**Comment by dcousens** [comment]
IMHO,  this is better off just being an example or documented somewhere,  then an actual extra export.

`/split` assumes the utxos provided are exactly what you want to use,  as you noticed.  I don't think the algorithm should be smarter?

It seems there are two algorithm types in play,  input selection,  and output selection.

`/accumulative` is an input selection module, 
`/blackjack` is an input selection module, 

`/break` is an output selection module,
`/split` is an output selection module,

*ALL* of them add a change output using `utils.finalize`.

**Comment by runn1ng** [comment]
How I see it conceptually.

Break and split are more "output generation" than "output selection"; you don't have an array of outputs that you filter, you have some data and you generate outputs out of that. "Type" - `Inputs + Data => Outputs` (incl. change)

The other modules are of "type" `Inputs + Outputs => False | (True + Inputs + Change value)` - You should not change the outputs in this case... you are adding change, but as a "special output".

I don't see how smart coin selection algorithm changes the outputs, except for telling user his output set is impossible...

**Comment by dcousens** [comment]
@runn1ng it might conceptually be the case that a user could have multiple change outputs,  not 1.

**Comment by runn1ng** [comment]
> it might conceptually be the case that a user could have multiple change outputs, not 1.

Hm, that might be possible I guess... not supported in the current iteration though. :)

So the pseudo-type for input selection algorithms is `Inputs + Outputs + Change address(es) => False | (True + Inputs + Outputs)`.

**Comment by dcousens** [comment]
@runn1ng e.g https://github.com/bitcoin/bips/blob/master/bip-0126.mediawiki

**Comment by dcousens** [comment]
> So the pseudo-type for input selection algorithms is Inputs + Outputs + Change address(es) => False | (True + Inputs + Outputs)

``` haskell
(Inputs | Outputs | Fee Rate | Maybe Outputs) -> Fee | (Inputs | Outputs | Fee)
```

I suppose?

**Comment by dcousens** [comment]
Do I close this,  or do you think its still worth while?

**Comment by runn1ng** [comment]
:+1: Closing. Maybe add issue "document send all", but not as this PR.

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/coinselect/issues/26

**Pull request closed without merging**
